import "server-only";
import { Prisma } from "@prisma/client";
import { prisma } from "@/server/db/client";
import { errors } from "@/server/lib/errors";
import { canonicalJson, sha256Hex } from "@/server/lib/crypto";
import { generateReceiptNumber } from "@/server/lib/ids";
import { record } from "@/server/audit";
import { getEnv } from "@/server/config/env";
import { getSetting } from "@/server/settings/service";
import {
  computeCost,
  getActivePricing,
  measurePeriod,
  persistCostRecord,
  type CostBreakdown,
} from "@/server/billing/service";

/**
 * Simulated receipts.
 *
 * A receipt is a permanent record of a calculation, so it must be reproducible:
 *   * every money value comes from the ONE arithmetic routine in billing/service.ts,
 *     never from a second formula,
 *   * the exact bytes and pricing are stored on the row,
 *   * a canonical payload is hashed with SHA-256 and the hash is stored, so
 *     /receipts/verify/{number} can prove the document was not altered.
 *
 * What a receipt is NOT: an official payment document. The disclaimer is mandatory,
 * the optional stamp is clearly a simulation stamp, and no provider authorisation,
 * transaction id or seal is ever fabricated. When an operator sets the provider label
 * to a third-party name, the disclaimer states explicitly that this document was not
 * issued by that provider.
 */

export const SIMULATION_STAMP_DEFAULT = "SIMULATION - NOT AN OFFICIAL PAYMENT DOCUMENT";

const BASE_DISCLAIMER =
  "This is a simulated receipt generated by the VWRAY control plane. It is not an official payment " +
  "document, it is not issued by any telecommunications provider, and it is not proof of payment. " +
  "No payment processor is connected to this installation.";

/** Exact wording the brief requires when the Wicore label is used. */
export const WICORE_DISCLAIMER =
  "Biên lai mô phỏng – không phải chứng từ thanh toán chính thức của Wicore.";

export function disclaimerFor(providerLabel: string): string {
  const isWicore = providerLabel.trim().toLowerCase().includes("wicore");
  return isWicore ? `${BASE_DISCLAIMER} ${WICORE_DISCLAIMER}` : BASE_DISCLAIMER;
}

export interface ReceiptCalculation {
  rawGb: number;
  optimizedGb: number;
  savedGb: number;
  freeQuotaGb: number;
  billableGb: number;
  baseFee: number;
  pricePerGb: number;
  subtotal: number;
  total: number;
  currency: string;
  formula: string;
}

export function calculationFrom(breakdown: CostBreakdown): ReceiptCalculation {
  const optimizedGb = Number(breakdown.optimizedBytes) / 1024 ** 3;
  return {
    rawGb: Math.round(breakdown.rawGb * 1000) / 1000,
    optimizedGb: Math.round(optimizedGb * 1000) / 1000,
    savedGb: Math.round((Number(breakdown.savedBytes) / 1024 ** 3) * 1000) / 1000,
    freeQuotaGb: breakdown.freeQuotaGb,
    billableGb: breakdown.billableGb,
    baseFee: breakdown.baseFee,
    pricePerGb: breakdown.pricePerGb,
    subtotal: Math.round(breakdown.billableGb * breakdown.pricePerGb * 100) / 100,
    total: breakdown.computedCost,
    currency: breakdown.currency,
    formula: breakdown.formula,
  };
}

export interface ReceiptView {
  id: string;
  receiptNumber: string;
  customerName: string;
  customerRef: string | null;
  deviceId: string | null;
  deviceLabel: string | null;
  configLabel: string | null;
  nodeLabel: string | null;
  periodStart: string;
  periodEnd: string;
  rawBytes: string;
  optimizedBytes: string;
  savedBytes: string;
  savingPct: number | null;
  savingsKind: "MEASURED" | "ESTIMATED";
  pricePerGb: number;
  baseFee: number;
  freeQuotaGb: number;
  billableGb: number;
  simulatedTotal: number;
  currency: string;
  verificationHash: string;
  verifyUrl: string;
  billingConfigId: string | null;
  stampEnabled: boolean;
  stampText: string | null;
  providerLabel: string;
  disclaimer: string;
  status: "DRAFT" | "ISSUED" | "VOID";
  source: "REAL" | "MOCK";
  generatedAt: string;
  generatedBy: string | null;
  calculation: ReceiptCalculation;
}

type ReceiptRow = {
  id: string;
  receiptNumber: string;
  customerName: string;
  customerRef: string | null;
  deviceId: string | null;
  configLabel: string | null;
  nodeLabel: string | null;
  periodStart: Date;
  periodEnd: Date;
  rawBytes: bigint;
  optimizedBytes: bigint;
  savedBytes: bigint;
  savingPct: number | null;
  savingsKind: "MEASURED" | "ESTIMATED";
  pricePerGb: Prisma.Decimal;
  baseFee: Prisma.Decimal;
  freeQuotaGb: Prisma.Decimal;
  billableGb: Prisma.Decimal;
  simulatedTotal: Prisma.Decimal;
  currency: string;
  verificationHash: string;
  billingConfigId: string | null;
  stampEnabled: boolean;
  stampText: string | null;
  providerLabel: string;
  disclaimer: string;
  status: "DRAFT" | "ISSUED" | "VOID";
  source: "REAL" | "MOCK";
  generatedAt: Date;
  generatedById: string | null;
};

function toView(row: ReceiptRow, deviceLabel?: string | null): ReceiptView {
  const breakdown: CostBreakdown = {
    rawBytes: row.rawBytes,
    optimizedBytes: row.optimizedBytes,
    savedBytes: row.savedBytes,
    savingPct: row.savingPct,
    rawGb: Number(row.rawBytes) / 1024 ** 3,
    billableGb: Number(row.billableGb),
    billableGbWithoutOptimization: 0,
    freeQuotaGb: Number(row.freeQuotaGb),
    baseFee: Number(row.baseFee),
    pricePerGb: Number(row.pricePerGb),
    currency: row.currency,
    computedCost: Number(row.simulatedTotal),
    costWithoutOptimization: 0,
    savedCost: 0,
    formula:
      `${row.currency} ${Number(row.baseFee).toFixed(2)} base fee + ` +
      `max(0, ${(Number(row.optimizedBytes) / 1024 ** 3).toFixed(6)} GB − ` +
      `${Number(row.freeQuotaGb).toFixed(6)} GB free quota) × ` +
      `${Number(row.pricePerGb).toFixed(4)} per GB = ${Number(row.simulatedTotal).toFixed(2)}`,
  };

  return {
    id: row.id,
    receiptNumber: row.receiptNumber,
    customerName: row.customerName,
    customerRef: row.customerRef,
    deviceId: row.deviceId,
    deviceLabel: deviceLabel ?? null,
    configLabel: row.configLabel,
    nodeLabel: row.nodeLabel,
    periodStart: row.periodStart.toISOString(),
    periodEnd: row.periodEnd.toISOString(),
    rawBytes: row.rawBytes.toString(),
    optimizedBytes: row.optimizedBytes.toString(),
    savedBytes: row.savedBytes.toString(),
    savingPct: row.savingPct,
    savingsKind: row.savingsKind,
    pricePerGb: Number(row.pricePerGb),
    baseFee: Number(row.baseFee),
    freeQuotaGb: Number(row.freeQuotaGb),
    billableGb: Number(row.billableGb),
    simulatedTotal: Number(row.simulatedTotal),
    currency: row.currency,
    verificationHash: row.verificationHash,
    verifyUrl: `${getEnv().APP_URL.replace(/\/$/, "")}/receipts/verify/${row.receiptNumber}`,
    billingConfigId: row.billingConfigId,
    stampEnabled: row.stampEnabled,
    stampText: row.stampText,
    providerLabel: row.providerLabel,
    disclaimer: row.disclaimer,
    status: row.status,
    source: row.source,
    generatedAt: row.generatedAt.toISOString(),
    generatedBy: row.generatedById,
    calculation: calculationFrom(breakdown),
  };
}

/**
 * The exact fields the verification hash covers.
 *
 * Built from an explicit object rather than "whatever the row contains", so adding a
 * column later cannot silently invalidate every existing receipt, and so the hash
 * cannot be influenced by fields a client controls.
 */
function canonicalPayloadOf(row: {
  receiptNumber: string;
  customerName: string;
  customerRef: string | null;
  periodStart: Date;
  periodEnd: Date;
  rawBytes: bigint;
  optimizedBytes: bigint;
  savedBytes: bigint;
  savingPct: number | null;
  savingsKind: string;
  pricePerGb: Prisma.Decimal;
  baseFee: Prisma.Decimal;
  freeQuotaGb: Prisma.Decimal;
  billableGb: Prisma.Decimal;
  simulatedTotal: Prisma.Decimal;
  currency: string;
  providerLabel: string;
  stampEnabled: boolean;
  disclaimer: string;
  status: string;
  generatedAt: Date;
  source: string;
}): string {
  return canonicalJson({
    v: 1,
    kind: "vwray.simulated-receipt",
    receiptNumber: row.receiptNumber,
    customerName: row.customerName,
    customerRef: row.customerRef,
    periodStart: row.periodStart.toISOString(),
    periodEnd: row.periodEnd.toISOString(),
    rawBytes: row.rawBytes.toString(),
    optimizedBytes: row.optimizedBytes.toString(),
    savedBytes: row.savedBytes.toString(),
    savingPct: row.savingPct,
    savingsKind: row.savingsKind,
    pricePerGb: row.pricePerGb.toFixed(4),
    baseFee: row.baseFee.toFixed(4),
    freeQuotaGb: row.freeQuotaGb.toFixed(4),
    billableGb: row.billableGb.toFixed(6),
    simulatedTotal: row.simulatedTotal.toFixed(4),
    currency: row.currency,
    providerLabel: row.providerLabel,
    stampEnabled: row.stampEnabled,
    disclaimer: row.disclaimer,
    status: row.status,
    generatedAt: row.generatedAt.toISOString(),
    source: row.source,
  });
}

export async function listReceipts(filters?: {
  page?: number;
  pageSize?: number;
  customerRef?: string | null;
  status?: string | null;
  preset?: string | null;
  from?: string | null;
  to?: string | null;
  search?: string | null;
}): Promise<{ items: ReceiptView[]; total: number }> {
  const { resolveRange } = await import("@/server/lib/time");
  const range =
    filters?.preset || filters?.from
      ? resolveRange({ preset: filters.preset, from: filters.from, to: filters.to })
      : null;

  const where = {
    ...(filters?.customerRef ? { customerRef: filters.customerRef } : {}),
    ...(filters?.status ? { status: filters.status as never } : {}),
    ...(range ? { generatedAt: { gte: range.start, lt: range.end } } : {}),
    ...(filters?.search
      ? {
          OR: [
            { customerName: { contains: filters.search, mode: "insensitive" as const } },
            { receiptNumber: { contains: filters.search, mode: "insensitive" as const } },
            { customerRef: { contains: filters.search, mode: "insensitive" as const } },
          ],
        }
      : {}),
  };

  const [rows, total] = await Promise.all([
    prisma.receipt.findMany({
      where,
      orderBy: { generatedAt: "desc" },
      skip: Math.max(0, (filters?.page ?? 1) - 1) * Math.min(filters?.pageSize ?? 25, 100),
      take: Math.min(filters?.pageSize ?? 25, 100),
    }),
    prisma.receipt.count({ where }),
  ]);

  const labels = await deviceLabels(rows.map((row) => row.deviceId));
  return { items: rows.map((row) => toView(row, labels.get(row.deviceId ?? ""))), total };
}

export async function getReceipt(id: string): Promise<ReceiptView> {
  const row = await prisma.receipt.findUnique({ where: { id } });
  if (!row) {
    const { errors } = await import("@/server/lib/errors");
    throw errors.notFound("Receipt");
  }
  const labels = await deviceLabels([row.deviceId]);
  return toView(row, labels.get(row.deviceId ?? ""));
}

export async function getReceiptByNumber(receiptNumber: string): Promise<ReceiptView> {
  const row = await prisma.receipt.findUnique({ where: { receiptNumber } });
  if (!row) {
    const { errors } = await import("@/server/lib/errors");
    throw errors.notFound("Receipt");
  }
  const labels = await deviceLabels([row.deviceId]);
  return toView(row, labels.get(row.deviceId ?? ""));
}

async function deviceLabels(ids: Array<string | null>): Promise<Map<string, string>> {
  const present = ids.filter((id): id is string => Boolean(id));
  if (present.length === 0) return new Map();
  const rows = await prisma.device.findMany({
    where: { id: { in: present } },
    select: { id: true, displayName: true },
  });
  return new Map(rows.map((row) => [row.id, row.displayName]));
}

export interface CreateReceiptInput {
  customerName: string;
  customerRef?: string | null;
  deviceId?: string | null;
  nodeId?: string | null;
  configLabel?: string | null;
  periodStart: Date;
  periodEnd: Date;
  stampEnabled?: boolean;
  providerLabel?: string | null;
  /** Optional per-receipt pricing overrides; defaults to the active configuration. */
  pricePerGb?: number | null;
  baseFee?: number | null;
  freeQuotaGb?: number | null;
  createCostRecord?: boolean;
  actorId: string;
  actorLabel: string;
  sourceIp?: string | null;
}

/**
 * Creates a simulated receipt from STORED traffic and STORED pricing.
 *
 * There is no path that accepts a total from the caller: if someone wants a different
 * number they change the pricing or the period, and the arithmetic runs again. That is
 * what makes the document traceable to stored billing data rather than to a form field.
 */
export async function createReceipt(
  input: CreateReceiptInput,
): Promise<{ receipt: ReceiptView; costRecordId: string | null }> {
  const name = input.customerName.trim().slice(0, 160);
  if (name.length === 0) throw errors.validation("A customer name is required.");
  if (input.periodEnd.getTime() <= input.periodStart.getTime()) {
    throw errors.validation("The receipt period must end after it starts.");
  }
  if (input.periodEnd.getTime() > Date.now() + 60_000) {
    throw errors.validation("A receipt cannot cover a period that has not started yet.");
  }

  const pricing = await getActivePricing();
  const effectivePricing = {
    currency: pricing.currency,
    pricePerGb: new Prisma.Decimal(input.pricePerGb ?? pricing.pricePerGb),
    baseFee: new Prisma.Decimal(input.baseFee ?? pricing.baseFee),
    freeQuotaGb: new Prisma.Decimal(input.freeQuotaGb ?? pricing.freeQuotaGb),
  };

  const device = input.deviceId
    ? await prisma.device.findUnique({ where: { id: input.deviceId } })
    : null;
  const node = input.nodeId ? await prisma.vpnNode.findUnique({ where: { id: input.nodeId } }) : null;

  const range = { start: input.periodStart, end: input.periodEnd };
  const dimKey = device ? `device:${device.id}` : "system";
  const measured = await measurePeriod({ range, dimKey, source: "REAL" });
  const breakdown = computeCost({ ...measured, pricing: effectivePricing });

  // Savings are only claimed as MEASURED when the data plane actually reported an
  // optimized volume. Otherwise the receipt states zero saved and marks it ESTIMATED.
  const measuredSavings = measured.optimizedBytes !== null;
  const savingsKind: "MEASURED" | "ESTIMATED" = measuredSavings ? "MEASURED" : "ESTIMATED";
  const savingPct = measuredSavings ? breakdown.savingPct : null;
  const providerLabel = (input.providerLabel ?? pricing.providerLabel).trim().slice(0, 60) || "VWRAY";
  const stampEnabled =
    input.stampEnabled ?? (await getSetting<boolean>("receipts.defaultStampEnabled"));
  const stampText = await getSetting<string>("receipts.stampText");
  const disclaimer = disclaimerFor(providerLabel);
  const generatedAt = new Date();

  const candidate = {
    receiptNumber: generateReceiptNumber(generatedAt),
    customerName: name,
    customerRef: input.customerRef?.trim().slice(0, 120) ?? null,
    periodStart: input.periodStart,
    periodEnd: input.periodEnd,
    rawBytes: breakdown.rawBytes,
    optimizedBytes: breakdown.optimizedBytes,
    savedBytes: measuredSavings ? breakdown.savedBytes : 0n,
    savingPct,
    savingsKind,
    pricePerGb: effectivePricing.pricePerGb,
    baseFee: effectivePricing.baseFee,
    freeQuotaGb: effectivePricing.freeQuotaGb,
    billableGb: new Prisma.Decimal(breakdown.billableGb),
    simulatedTotal: new Prisma.Decimal(breakdown.computedCost),
    currency: breakdown.currency,
    providerLabel,
    stampEnabled,
    disclaimer,
    status: "ISSUED" as const,
    generatedAt,
    source: "REAL" as const,
  };

  const payloadCanonical = canonicalPayloadOf(candidate);
  const verificationHash = sha256Hex(payloadCanonical);

  const created = await prisma.receipt.create({
    data: {
      ...candidate,
      deviceId: device?.id ?? null,
      configLabel: input.configLabel?.slice(0, 120) ?? null,
      nodeLabel: node?.name ?? null,
      payloadCanonical,
      verificationHash,
      stampText,
      billingConfigId: pricing.configId,
      generatedById: input.actorId,
    },
  });

  const costRecordId = input.createCostRecord
    ? (
        await persistCostRecord({
          scope: device ? "DEVICE" : "SYSTEM",
          scopeRefId: device?.id ?? null,
          label: device ? device.displayName : `System ${name}`,
          range,
          dimKey,
          source: "REAL",
          actorId: input.actorId,
          actorLabel: input.actorLabel,
          sourceIp: input.sourceIp,
        })
      ).id
    : null;

  await record({
    actor: { type: "USER", id: input.actorId, label: input.actorLabel },
    action: "receipt.created",
    resource: "receipt",
    resourceId: created.id,
    result: "SUCCESS",
    sourceIp: input.sourceIp,
    metadata: {
      receiptNumber: created.receiptNumber,
      customer: name,
      periodStart: candidate.periodStart.toISOString(),
      periodEnd: candidate.periodEnd.toISOString(),
      simulatedTotal: candidate.simulatedTotal.toString(),
      currency: candidate.currency,
      savingsKind,
      stampEnabled,
      providerLabel,
      verificationHash,
      simulated: true,
    },
  });

  return { receipt: await getReceipt(created.id), costRecordId };
}

export interface VerificationResult {
  valid: boolean;
  receiptNumber: string;
  generatedAt: string;
  simulatedTotal: number;
  currency: string;
  rawBytes: string;
  optimizedBytes: string;
  savedBytes: string;
  periodStart: string;
  periodEnd: string;
  status: string;
  providerLabel: string;
  stampEnabled: boolean;
  disclaimer: string;
  integrity: {
    algorithm: "SHA-256";
    hash: string;
    /** Stored hash matches the hash recomputed from the stored canonical payload. */
    matches: boolean;
    /** Canonical payload rebuilt from the columns matches the stored canonical payload. */
    canonicalMatches: boolean;
    canonical: string;
  };
  platformStatement: string;
  checkedAt: string;
}

/**
 * Public verification.
 *
 * Two independent checks run, because they answer different questions:
 *   1. matches         - has the canonical payload been modified since it was issued?
 *   2. canonicalMatches - do the visible columns still agree with that payload?
 *
 * A row could survive check 1 while its displayable columns were edited, or vice
 * versa; only both together justify the word "valid". The verifier never trusts the
 * stored hash alone: it recomputes from the stored canonical string, and rebuilds the
 * canonical string from the columns.
 */
export async function verifyReceipt(receiptNumber: string): Promise<VerificationResult> {
  const row = await prisma.receipt.findUnique({ where: { receiptNumber } });
  const checkedAt = new Date().toISOString();

  if (!row) {
    throw errors.notFound("Receipt");
  }

  const recomputedHash = sha256Hex(row.payloadCanonical);
  const rebuiltCanonical = canonicalPayloadOf(row);
  const matches = recomputedHash === row.verificationHash;
  const canonicalMatches = rebuiltCanonical === row.payloadCanonical;

  return {
    valid: matches && canonicalMatches,
    receiptNumber: row.receiptNumber,
    generatedAt: row.generatedAt.toISOString(),
    simulatedTotal: Number(row.simulatedTotal),
    currency: row.currency,
    rawBytes: row.rawBytes.toString(),
    optimizedBytes: row.optimizedBytes.toString(),
    savedBytes: row.savedBytes.toString(),
    periodStart: row.periodStart.toISOString(),
    periodEnd: row.periodEnd.toISOString(),
    status: row.status,
    providerLabel: row.providerLabel,
    stampEnabled: row.stampEnabled,
    disclaimer: row.disclaimer,
    integrity: {
      algorithm: "SHA-256",
      hash: row.verificationHash,
      matches,
      canonicalMatches,
      canonical: row.payloadCanonical,
    },
    platformStatement:
      "This is a simulated receipt generated by the VWRAY control plane. It is not an official payment " +
      "document and does not prove that any payment was made.",
    checkedAt,
  };
}

/** Marks a receipt VOID. The row and its hash are kept: a voided document is still evidence. */
export async function voidReceipt(input: {
  id: string;
  reason: string;
  actorId: string;
  actorLabel: string;
  sourceIp?: string | null;
}): Promise<ReceiptView> {
  const row = await prisma.receipt.findUnique({ where: { id: input.id } });
  if (!row) throw errors.notFound("Receipt");
  if (row.status === "VOID") throw errors.invalidState("This receipt is already void.");

  await prisma.receipt.update({ where: { id: row.id }, data: { status: "VOID" } });

  await record({
    actor: { type: "USER", id: input.actorId, label: input.actorLabel },
    action: "receipt.voided",
    resource: "receipt",
    resourceId: row.id,
    result: "SUCCESS",
    sourceIp: input.sourceIp,
    metadata: { reason: input.reason, receiptNumber: row.receiptNumber, simulated: true },
  });

  return getReceipt(row.id);
}
